# StashWise Common Library

[![standard-readme compliant](https://img.shields.io/badge/readme%20style-standard-brightgreen.svg?style=flat-square)](https://github.com/RichardLitt/standard-readme)

# Table of Contents

-   [General Info](#general-info)

-   [Technologies](#technologies)

-   [Status](#status)

### General Info

Shared common library for Stashwise Savings microservice

### Technologies

This project is built with:

-   [Nodejs/ExpressJS](https://expressjs.com)

### Status

Status page generated by BetterUptime: [View Status Page](https://stashwise.betteruptime.com)
